# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: format code with black
      uses: psf/black@stable
    - name: Lint with flake8
      run: |
        flake8 . --exclude=venv --ignore=W503,W291,E501
    - name: Test with pytest
      run: |
        pytest tests
